### ISSUE TITLE
cannot reset password

### ISSUE THREAD

**Issue by carueda** [mmisw/orr-ont#34]
Noticed by Nonong with the XDOMEs ORR instance.

By looking at the log (`docker -f logs orr-ont`) I note that the "standard" call to retrieve the base URL of the application (used to compose the next "your password has been reset" html page) failed with a NPE:

```
Exception in thread "Thread-11" java.lang.NullPointerException
	at org.apache.catalina.connector.Request.getRequestURL(Request.java:2314)
	at org.apache.catalina.connector.RequestFacade.getRequestURL(RequestFacade.java:868)
	at org.mmisw.orr.ont.app.OrrOntStack$class.getMyBaseUrl(OrrOntStack.scala:89)
	at org.mmisw.orr.ont.app.BaseController.getMyBaseUrl(BaseController.scala:11)
	at org.mmisw.orr.ont.app.UserController$$anonfun$4$$anon$2.run(UserController.scala:60)
	at java.lang.Thread.run(Thread.java:745)
```

I re-started the application and tried to reproduce (with my carueda account). The NPE is not happening. but I cannot get to advance to the "your password has been reset" html page.

@fgayanilo FYI

**Comment by carueda** [comment]
Fix installed on the xdomes instance.  orr-ont version 3.1.7.  (note: the portal still shows v3.1.6)
